OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: RevenueOrg
    Domain: revenue.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: BankOrg
    Domain: bank.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: CourtOrg
    Domain: court.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
